### ISSUE TITLE
Using React Components installed through NPM

### ISSUE THREAD

**Issue by afang** [meteorhacks/npm#122]
How would I go about using a [React component](http://react-components.com/component/react-center) that is installed through NPM?

```
import Center from 'react-center';

Metabar = React.createClass({
    getInitialState() {
        return {
            themeStatus: `Loading themes...`
        }
    },
    render() {
        return (
            <div className="ui text menu metabar">
	        <div className="ui basic modal theme-import">
	        <Center>
	        <h1><i className="notched circle loading icon"></i> {this.state.themeStatus}</h1>
	        </Center>
	        </div>
	        <a className="item right menu">
	        <button className="large ui icon button help circular">
	        <i className="help icon"></i>
	        </button>
	        </a>
	        </div>
            )
    }
});
```

**Comment by sgtpepper43** [comment]
http://react-in-meteor.readthedocs.org/en/latest/client-npm/

By the way, if you just add the word `Meteor` to your issue title and search google, that's literally the first link that comes up.

**Comment by afang** [comment]
I was asking if there was a better way than Browserify + Meteorhacks:npm since it's an outdated solution. Better to upgrade Meteor to 1.3b since it has import modules built-in.
