### ISSUE TITLE
`updating npm dependencies` step stuck in infinite loop

### ISSUE THREAD

**Issue by sgtpepper43** [meteorhacks/npm#124]
My app just keeps building the dependencies over and over and over. A comment in #105 mentions this, but having the focus of the issue be "my app is completely broken" makes it a bit more urgent than "it adds this thing back in, weird".

**Comment by sgtpepper43** [comment]
Re-cloning the entire project from github seems to have fixed the problem. Though it still sounds like something that needs to be looked into.

**Comment by sgtpepper43** [comment]
This package is basically deprecated with the 1.3 update, so I'm just gonna close this (not that anybody looked at this ever)

**Comment by nerdvibe** [comment]
This happened to me with a package on Meteor 1.4.3.1 

In order to get rid of it, I've just deleted the .npm folder of the package.
