### ISSUE TITLE
Add Meteor 1.3 info to readme

### ISSUE THREAD

**Issue by lorensr** [meteorhacks/npm#129]
Thought you might want to recommend to new people looking at the package to use Meteor 1.3 npm integration. Also, for people transitioning to 1.3 and removing this package, perhaps note:

`Async.wrap(delayedMessge);` -> `Meteor.wrapAsync(delayedMessage)`
`Async.wrap(github.user, 'getFrom');` -> `Meteor.wrapAsync(github.user.getFrom, github.user)`

**Comment by arunoda** [comment]
Yeah sure.

**Comment by arunoda** [comment]
Added: https://github.com/meteorhacks/npm#using-with-meteor-13
