### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by elbowz** [meteorhacks/npm#18]
HI,

 if package is installed:
```npm install -g meteor-npm #single time operation
meteor-npm #type inside your project```

Is there some procedure for uninstall from project?
If use "meteor remove npm" packages/npm remain...

thanks in advance!

**Comment by pascoual** [comment]
Should work:
meteor remove npm-container


I've done:
rm -rf packages/npm-container
+ remove npm-container manualy in .meteor/packages file

**Comment by arunoda** [comment]
Yes. May be from the git as well.
Also remove meteorhacks:npm
