### ISSUE TITLE
Using Git URL's

### ISSUE THREAD

**Issue by wbashir** [meteorhacks/npm#4]
How can we use git url's as dependencies. I tried 

`"stripe": "git://github.com/abh/node-stripe.git"`

and i get an error : 

`ERROR: packages.json parsing error [ Must declare exact version of npm package dependency: stripe@git://github.com/abh/node-stripe.git ]`?

**Comment by mateodelnorte** [comment]
Hi, just touching base on this as I'm finding it's still a problem. 

Totally right that this works by using a commit SHA, but restricting to that format hinders best practices - namely the ability to specify tarball by a tag name. The corresponding syntax and convention for specifying a private node module is as follows:
```
    "module-name": "git+ssh://git@github.com/account/module-name.git#my-tag-name",
```
In practice, many people/companies will use their tag names to stand in as version numbers:
```
    "module-name": "git+ssh://git@github.com/account/module-name.git#v0.0.1",
```
I really don't think `exports.isUrlWithSha()` makes any sense here: https://github.com/meteor/meteor/blob/832e6fe44f3635cae060415d6150c0105f2bf0f6/tools/utils.js#L502

**Comment by nicolamr** [comment]
Apparently the same is true for

    "module-name": "file://..."

**Comment by morenoh149** [comment]
What is an absolute version? I tried
```
{
  "base64-string-s3": "https://github.com/morenoh149/base64-string-s3.git#master"
}
```
