### ISSUE TITLE
Object #<Object> has no method 'npmRequire' 

### ISSUE THREAD

**Issue by mstn** [meteorhacks/npm#55]
Hi all,

after updating to 0.9.3.1 I notice this blocking error when launching the application

```
W20141006-10:59:55.494(2)? (STDERR) /myhome/.meteor/packages/meteor-  tool/.1.0.33.2d4d5z++os.osx.x86_64+web.browser+web.cordova/meteor-tool-  os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20141006-10:59:55.494(2)? (STDERR)                         throw(ex);
W20141006-10:59:55.495(2)? (STDERR)                               ^
W20141006-10:59:55.495(2)? (STDERR) TypeError: Object #<Object> has no method 'npmRequire'
W20141006-10:59:55.495(2)? (STDERR)     at app/server/bootstrap.js:8:17
W20141006-10:59:55.495(2)? (STDERR)     at  /myprojectdir/.meteor/local/build/programs/server/boot.js:175:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

I didn't change the code and it works with 0.9.3. 

I removed .meteor and .meteor/local/build, but the problem persists.

**Comment by aashuagg** [comment]
I am facing the same issue. Is it that I can call Meteor.npmRequire only in packages? I am trying to call it in a server side file to use aws-sdk as below:

var AWS = Meteor.npmRequire('aws-sdk');

Also I have added aws-sdk in packages.json:

{
  ...,
  ...,
  "aws-sdk" : "2.1.2"
}

**Comment by dcsan** [comment]
Also getting this problem, with a very simple app. It's strange as i have used npmRequire before with much more complex apps

**Comment by nicejwjin** [comment]
I don't understand why this simple bug(I think) still exists;
You can solve this by deleting packages directory and re-launch your app.
It looks the package can't make the index.js and packages.js files in the packages/npm-container/.
npm-container will make the directories and files again.

**Comment by keyscores** [comment]
Can we add this to the DOCS, I'm on meteor 1.1.0.3 and still having this issue.

**Comment by JulianKingman** [comment]
I also had this issue. Deleting the files and reinstalling seemed to fix it.
