### ISSUE TITLE
Same benefits Npm.require()?

### ISSUE THREAD

**Issue by trusktr** [meteorhacks/npm#77]
Does this have the same benefits as using Npm.require() does for smart packages?

**Comment by arunoda** [comment]
You don't need to use this inside a package. Define npm packages you need
with Npm.depends and use Npm.require

**Comment by trusktr** [comment]
@arunoda I knew that but what I mean is that does this provide the same benefits for applications as Npm.require does for smart packages?

**Comment by arunoda** [comment]
Yes.
