### ISSUE TITLE
Is there any client side solution?

### ISSUE THREAD

**Issue by trusktr** [meteorhacks/npm#78]
How can we use NPM modules on the client side?

**Comment by cranesandcaff** [comment]
Combine it with: https://atmospherejs.com/cosmos/browserify

**Comment by trusktr** [comment]
@cranesandcaff I started [`rocket:module`](https://atmospherejs.com/rocket/module) to solve the problem. I saw `cosmos:browserify` which inspired me. `Rocket:module` picks up by handling npm dependencies using vanilla npm (not limited to absolute versions like with `Npm.depends`) and code splitting to share libraries among all bundles of all Meteor packages in a given app. I'll put more info in the [Meteor forum thread](https://forums.meteor.com/t/new-package-rocket-module-to-provide-cjs-amd-es6-modules-for-meteor-packages-with-shared-npm-dependencies/4620/3) as I go, and finally I'll update the README when it's ready. (:

**Comment by arunoda** [comment]
That's great.

By leveraging `cosmos:browserify` we'll have browserify support soon. So,
we can use `Meteor.npmRequire` on the client too.

**Comment by trusktr** [comment]
@arunoda But that means all of your code has `Meteor.npmRequire` in it, not compatible outside of Meteor. I'd rather write all my code with vanilla CJS or ES6 syntax and have it work in Meteor.

**Comment by arunoda** [comment]
I agree.
This is not an all in one solution.
That's why I think your solution is pretty useful.

**Comment by trusktr** [comment]
@arunoda I've run into a problem. I was initially developing `rocket:module` using locally installed packages inside of my test application, which would allow me to inspect the current application (looking in the filesystem) to determine build steps. But now I've realized that packages need to be compiled without knowing anything about the applications that they will run in.

I think that instead of relying solely on a build plugin, I now need to do stuff at server-side runtime to handle the final bundles. This is becoming more complicated than I originally thought, because I would need to make sure that the bundles for each package are loaded in the proper order inline with all other package code so that all package dependencies are present when needed for all packages in the app.

Any ideas? Do you know of any hooks to do stuff before runtime build happens, etc?

**Comment by arunoda** [comment]
I don't there any hooks. But you can write plugins. There is a plugin
example and this package and browserify package as well.

**Comment by trusktr** [comment]
@arunoda So I'm looking what this plugin does. The build plugin creates a new package, `./packages/npm-container`. So, this build plugin runs during app-build-time only (hence the `canProceed` function to make sure of that). So what I'm wondering is, how is it that you can add a package to Meteor during app-build-time and that package will still be included in the build? Is it just a coincidence that Meteor won't check for local packages until after executing the build plugin (`init_npm.js`), and you took advantage of that?

**Comment by trusktr** [comment]
nevermind, I see echo.sync("\nnpm-container", ">>", ".meteor/packages");, so I guess we got lucky that Meteor doesn't even look at .meteor/packages until after the build plugin code executed.

**Comment by trusktr** [comment]
@arunoda Turns out hooks aren't the solution. This is the solution: https://quip.com/YLcCAxtjuwsL

That will be amazing!!
